import type {GetStaticProps, NextPage} from 'next'
import Head from 'next/head'
import {loadTranslation} from "../utils";
import {Trans} from "@lingui/macro";


export const getStaticProps: GetStaticProps = async (ctx) => {
    const translation = await loadTranslation(
        ctx.locale!,
        process.env.NODE_ENV === "production",
    );

    return {
        props: {
            translation,
        },
    };
};

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div style={{height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
                <Trans>Это единственный текст</Trans>
            </div>
        </div>
    )
}

export default Home
